In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data_for_predictions.csv')
df.head()

,Unnamed: 0,id,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,months_modif_prod,months_renewal,channel_MISSING,channel_ewpakwlliwisiwduibdlfmalxowmwpci,channel_foosdfpfkusacimwkcsosbicdxkicaua,channel_lmkebamcaaclubfxadlmueccxoimlema,channel_usilxuppasemubllopkaafesmlibmsdf,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw
0,0,24011ae4ebbe3035111d65fa7c15bc57,0.000000,4.739944,0.000000,0.000000,0.0,0.444045,0.114481,0.098142,...,2,6,0,0,1,0,0,0,0,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,3.668479,0.000000,0.000000,2.280920,0.0,1.237292,0.145711,0.000000,...,76,4,1,0,0,0,0,1,0,0
2,2,764c75f661154dac3a6c254cd082ea7d,2.736397,0.000000,0.000000,1.689841,0.0,1.599009,0.165794,0.087899,...,68,8,0,0,1,0,0,1,0,0
3,3,bba03439a292a1e166f80264c16191cb,3.200029,0.000000,0.000000,2.382089,0.0,1.318689,0.146694,0.000000,...,69,9,0,0,0,1,0,1,0,0
4,4,149d57cf92fc41cf94415803a877cb4b,3.646011,0.000000,2.721811,2.650065,0.0,2.122969,0.116900,0.100015,...,71,9,1,0,0,0,0,1,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 64 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Unnamed: 0                                  14606 non-null  int64
 1   id                                          14606 non-null  object
 2   cons_12m                                    14606 non-null  float64
 3   cons_gas_12m                                14606 non-null  float64
 4   cons_last_month                             14606 non-null  float64
 5   forecast_cons_12m                           14606 non-null  float64
 6   forecast_discount_energy                    14606 non-null  float64
 7   forecast_meter_rent_12m                     14606 non-null  float64
 8   forecast_price_energy_off_peak              14606 non-null  float64
 9   forecast_price_energy_peak                  14606 non-null  float64
 10  forecast_price_pow_off_peak                 14606 non-null  float64
 11  has_gas                                     14606 non-null  int64
 12  imp_cons                                    14606 non-null  float64
 13  margin_gross_pow_ele                        14606 non-null  float64
 14  margin_net_pow_ele                          14606 non-null  float64
 15  nb_prod_act                                 14606 non-null  int64
 16  net_margin                                  14606 non-null  float64
 17  pow_max                                     14606 non-null  float64
 18  var_year_price_off_peak_var                 14606 non-null  float64
 19  var_year_price_peak_var                     14606 non-null  float64
 20  var_year_price_mid_peak_var                 14606 non-null  float64
 21  var_year_price_off_peak_fix                 14606 non-null  float64
 22  var_year_price_peak_fix                     14606 non-null  float64
 23  var_year_price_mid_peak_fix                 14606 non-null  float64
 24  var_year_price_off_peak                     14606 non-null  float64
 25  var_year_price_peak                         14606 non-null  float64
 26  var_year_price_mid_peak                     14606 non-null  float64
 27  var_6m_price_off_peak_var                   14606 non-null  float64
 28  var_6m_price_peak_var                       14606 non-null  float64
 29  var_6m_price_mid_peak_var                   14606 non-null  float64
 30  var_6m_price_off_peak_fix                   14606 non-null  float64
 31  var_6m_price_peak_fix                       14606 non-null  float64
 32  var_6m_price_mid_peak_fix                   14606 non-null  float64
 33  var_6m_price_off_peak                       14606 non-null  float64
 34  var_6m_price_peak                           14606 non-null  float64
 35  var_6m_price_mid_peak                       14606 non-null  float64
 36  churn                                       14606 non-null  int64
 37  offpeak_diff_dec_january_energy             14606 non-null  float64
 38  offpeak_diff_dec_january_power              14606 non-null  float64
 39  off_peak_peak_var_mean_diff                 14606 non-null  float64
 40  peak_mid_peak_var_mean_diff                 14606 non-null  float64
 41  off_peak_mid_peak_var_mean_diff             14606 non-null  float64
 42  off_peak_peak_fix_mean_diff                 14606 non-null  float64
 43  peak_mid_peak_fix_mean_diff                 14606 non-null  float64
 44  off_peak_mid_peak_fix_mean_diff             14606 non-null  float64
 45  off_peak_peak_var_max_monthly_diff          14606 non-null  float64
 46  peak_mid_peak_var_max_monthly_diff          14606 non-null  float64
 47  off_peak_mid_peak_var_max_monthly_diff      14606 non-null  float64
 48  off_peak_peak_fix_max_monthly_diff          14606 non-null  float64
 49  peak_mid_peak_fix_max_monthly_diff          14606 non-null  float64
 50  off_peak_mid_peak_fix_max_monthly_diff      14606 non-null  float64
 51  tenure                                      14606 non-null  int64
 52  months_activ                                14606 non-null  int64
 53  months_to_end                               14606 non-null  int64
 54  months_modif_prod                           14606 non-null  int64
 55  months_renewal                              14606 non-null  int64
 56  channel_MISSING                             14606 non-null  int64
 57  channel_ewpakwlliwisiwduibdlfmalxowmwpci    14606 non-null  int64
 58  channel_foosdfpfkusacimwkcsosbicdxkicaua    14606 non-null  int64
 59  channel_lmkebamcaaclubfxadlmueccxoimlema    14606 non-null  int64
 60  channel_usilxuppasemubllopkaafesmlibmsdf    14606 non-null  int64
 61  origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws  14606 non-null  int64
 62  origin_up_ldkssxwpmemidmecebumciepifcamkci  14606 non-null  int64
 63  origin_up_lxidpiddsbxsbosboudacockeimpuepw  14606 non-null  int64
dtypes: float64(46), int64(17), object(1)
memory usage: 7.1+ MB

In [5]:
df.isnull().sum()

Unnamed: 0                                    0
id                                            0
cons_12m                                      0
cons_gas_12m                                  0
cons_last_month                               0
                                             ..
channel_lmkebamcaaclubfxadlmueccxoimlema      0
channel_usilxuppasemubllopkaafesmlibmsdf      0
origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws    0
origin_up_ldkssxwpmemidmecebumciepifcamkci    0
origin_up_lxidpiddsbxsbosboudacockeimpuepw    0
Length: 64, dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['churn'].value_counts()

churn
0    13187
1     1419
Name: count, dtype: int64

In [8]:
df.head()

,Unnamed: 0,id,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,months_modif_prod,months_renewal,channel_MISSING,channel_ewpakwlliwisiwduibdlfmalxowmwpci,channel_foosdfpfkusacimwkcsosbicdxkicaua,channel_lmkebamcaaclubfxadlmueccxoimlema,channel_usilxuppasemubllopkaafesmlibmsdf,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw
0,0,24011ae4ebbe3035111d65fa7c15bc57,0.000000,4.739944,0.000000,0.000000,0.0,0.444045,0.114481,0.098142,...,2,6,0,0,1,0,0,0,0,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,3.668479,0.000000,0.000000,2.280920,0.0,1.237292,0.145711,0.000000,...,76,4,1,0,0,0,0,1,0,0
2,2,764c75f661154dac3a6c254cd082ea7d,2.736397,0.000000,0.000000,1.689841,0.0,1.599009,0.165794,0.087899,...,68,8,0,0,1,0,0,1,0,0
3,3,bba03439a292a1e166f80264c16191cb,3.200029,0.000000,0.000000,2.382089,0.0,1.318689,0.146694,0.000000,...,69,9,0,0,0,1,0,1,0,0
4,4,149d57cf92fc41cf94415803a877cb4b,3.646011,0.000000,2.721811,2.650065,0.0,2.122969,0.116900,0.100015,...,71,9,1,0,0,0,0,1,0,0

In [11]:
X = df.drop(['id', 'churn'], axis=1)
y = df['churn']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
X.select_dtypes(include=['object', 'datetime']).columns

Index([], dtype='object')

In [14]:
from sklearn.model_selection import train_test_split
train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

[       Unnamed: 0  cons_12m  cons_gas_12m  cons_last_month  forecast_cons_12m  \
 6834         6834  4.211414      0.000000         0.000000           3.378941
 5540         5540  4.652362      4.257319         4.162056           3.818794
 12024       12024  4.176439      0.000000         0.000000           3.160823
 12977       12977  4.567356      3.730136         3.469527           3.574744
 1437         1437  4.249467      0.000000         0.000000           3.256614
 ...           ...       ...           ...              ...                ...
 12134       12134  4.278799      0.000000         3.451940           3.167167
 13759       13759  1.531479      0.000000         0.698970           0.771587
 11997       11997  4.036509      0.000000         3.444357           2.418069
 5514         5514  3.294025      0.000000         2.201397           2.173769
 9452         9452  3.826658      0.000000         0.000000           3.106643

        forecast_discount_energy  forecast_meter_rent_12m  \
 6834                        0.0                 1.207634
 5540                        0.0                 1.269513
 12024                       0.0                 1.230960
 12977                       0.0                 2.121822
 1437                        0.0                 2.080663
 ...                         ...                      ...
 12134                      28.0                 1.305781
 13759                       0.0                 1.246252
 11997                       0.0                 1.311330
 5514                        0.0                 2.123035
 9452                       28.0                 1.265525

        forecast_price_energy_off_peak  forecast_price_energy_peak  \
 6834                         0.142819                    0.000000
 5540                         0.142819                    0.000000
 12024                        0.162133                    0.083488
 12977                        0.115174                    0.098837
 1437                         0.116509                    0.101397
 ...                               ...                         ...
 12134                        0.211278                    0.107406
 13759                        0.145884                    0.000000
 11997                        0.146694                    0.000000
 5514                         0.114604                    0.098262
 9452                         0.186188                    0.000000

        forecast_price_pow_off_peak  ...  months_modif_prod  months_renewal  \
 6834                     44.311378  ...                 65               5
 5540                     44.311378  ...                 77               5
 12024                    44.311378  ...                  3               1
 12977                    40.606701  ...                126               6
 1437                     40.606701  ...                  7               2
 ...                            ...  ...                ...             ...
 12134                    46.803878  ...                  2               6
 13759                    44.311378  ...                 70              10
 11997                    44.311378  ...                 69               9
 5514                     40.606701  ...                  6               5
 9452                     45.806878  ...                  0              10

        channel_MISSING  channel_ewpakwlliwisiwduibdlfmalxowmwpci  \
 6834                 0                                         0
 5540                 1                                         0
 12024                1                                         0
 12977                1                                         0
 1437                 0                                         0
 ...                ...                                       ...
 12134                1                                         0
 13759                0                                         0
 11997                0                                         0
 5514                 1                                         0
 9452                 0                                         0

        channel_foosdfpfkusacimwkcsosbicdxkicaua  \
 6834                                          1
 5540                                          0
 12024                                         0
 12977                                         0
 1437                                          0
 ...                                         ...
 12134                                         0
 13759                                         1
 11997                                         1
 5514                                          0
 9452                                          1

        channel_lmkebamcaaclubfxadlmueccxoimlema  \
 6834                                          0
 5540                                          0
 12024                                         0
 12977                                         0
 1437                                          0
 ...                                         ...
 12134                                         0
 13759                                         0
 11997                                         0
 5514                                          0
 9452                                          0

        channel_usilxuppasemubllopkaafesmlibmsdf  \
 6834                                          0
 5540                                          0
 12024                                         0
 12977                                         0
 1437                                          1
 ...                                         ...
 12134                                         0
 13759                                         0
 11997                                         0
 5514                                          0
 9452                                          0

        origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws  \
 6834                                            0
 5540                                            0
 12024                                           1
 12977                                           0
 1437                                            0
 ...                                           ...
 12134                                           0
 13759                                           1
 11997                                           1
 5514                                            0
 9452                                            0

        origin_up_ldkssxwpmemidmecebumciepifcamkci  \
 6834                                            0
 5540                                            1
 12024                                           0
 12977                                           1
 1437                                            0
 ...                                           ...
 12134                                           1
 13759                                           0
 11997                                           0
 5514                                            1
 9452                                            0

        origin_up_lxidpiddsbxsbosboudacockeimpuepw
 6834                                            1
 5540                                            0
 12024                                           0
 12977                                           0
 1437                                            1
 ...                                           ...
 12134                                           0
 13759                                           0
 11997                                           0
 5514                                            0
 9452                                            1

 [11684 rows x 62 columns],
        Unnamed: 0  cons_12m  cons_gas_12m  cons_last_month  forecast_cons_12m  \
 633           633  4.464743      0.000000         3.637690           3.479168
 8040         8040  6.425284      4.942772         5.473655           3.694189
 14584       14584  4.381693      0.000000         3.364176           3.658832
 5049         5049  5.308415      0.000000         4.136721           3.395676
 12422       12422  3.623146      4.083968         0.000000           2.797032
 ...           ...       ...           ...              ...                ...
 11214       11214  4.317248      0.000000         3.765594           0.000000
 10726       10726  4.735000      0.000000         3.515741           3.736042
 12390       12390  3.717587      0.000000         0.000000           2.879956
 10617       10617  5.105098      0.000000         4.206313           3.658571
 4337         4337  3.857815      0.000000         0.000000           2.961393

        forecast_discount_energy  forecast_meter_rent_12m  \
 633                         0.0                 1.962369
 8040                        0.0                 2.120738
 14584                      24.0                 1.318481
 5049                        0.0                 2.122805
 12422                       0.0                 1.203577
 ...                         ...                      ...
 11214                       0.0                 0.000000
 10726                       0.0                 2.123754
 12390                       0.0                 1.612466
 10617                       0.0                 2.169116
 4337                        0.0                 1.309417

        forecast_price_energy_off_peak  forecast_price_energy_peak  \
 633                          0.115182                    0.098841
 8040                         0.115174                    0.098837
 14584                        0.186188                    0.000000
 5049                         0.116910                    0.100572
 12422                        0.144902                    0.000000
 ...                               ...                         ...
 11214                        0.000600                    0.000000
 10726                        0.113323                    0.096984
 12390                        0.140621                    0.000000
 10617                        0.114481                    0.098142
 4337                         0.142881                    0.000000

        forecast_price_pow_off_peak  ...  months_modif_prod  months_renewal  \
 633                      40.606701  ...                  7               6
 8040                     40.606701  ...                 19               7
 14584                    45.806878  ...                 20               8
 5049                     40.606701  ...                 18               6
 12422                    44.311378  ...                  6               3
 ...                            ...  ...                ...             ...
 11214                     0.000000  ...                  2               0
 10726                    40.606701  ...                147               3
 12390                    44.311378  ...                 77               3
 10617                    40.606701  ...                 43               7
 4337                     45.308378  ...                  4               2

        channel_MISSING  channel_ewpakwlliwisiwduibdlfmalxowmwpci  \
 633                  0                                         0
 8040                 0                                         0
 14584                1                                         0
 5049                 1                                         0
 12422                1                                         0
 ...                ...                                       ...
 11214                1                                         0
 10726                1                                         0
 12390                0                                         0
 10617                0                                         0
 4337                 0                                         0

        channel_foosdfpfkusacimwkcsosbicdxkicaua  \
 633                                           1
 8040                                          0
 14584                                         0
 5049                                          0
 12422                                         0
 ...                                         ...
 11214                                         0
 10726                                         0
 12390                                         0
 10617                                         1
 4337                                          1

        channel_lmkebamcaaclubfxadlmueccxoimlema  \
 633                                           0
 8040                                          1
 14584                                         0
 5049                                          0
 12422                                         0
 ...                                         ...
 11214                                         0
 10726                                         0
 12390                                         1
 10617                                         0
 4337                                          0

        channel_usilxuppasemubllopkaafesmlibmsdf  \
 633                                           0
 8040                                          0
 14584                                         0
 5049                                          0
 12422                                         0
 ...                                         ...
 11214                                         0
 10726                                         0
 12390                                         0
 10617                                         0
 4337                                          0

        origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws  \
 633                                             0
 8040                                            0
 14584                                           0
 5049                                            0
 12422                                           0
 ...                                           ...
 11214                                           0
 10726                                           0
 12390                                           0
 10617                                           0
 4337                                            0

        origin_up_ldkssxwpmemidmecebumciepifcamkci  \
 633                                             0
 8040                                            1
 14584                                           0
 5049                                            1
 12422                                           0
 ...                                           ...
 11214                                           1
 10726                                           1
 12390                                           1
 10617                                           0
 4337                                            0

        origin_up_lxidpiddsbxsbosboudacockeimpuepw
 633                                             1
 8040                                            0
 14584                                           1
 5049                                            0
 12422                                           1
 ...                                           ...
 11214                                           0
 10726                                           0
 12390                                           0
 10617                                           1
 4337                                            1

 [2922 rows x 62 columns],
 6834     0
 5540     0
 12024    0
 12977    0
 1437     0
         ..
 12134    0
 13759    0
 11997    0
 5514     1
 9452     1
 Name: churn, Length: 11684, dtype: int64,
 633      0
 8040     0
 14584    0
 5049     0
 12422    0
         ..
 11214    0
 10726    0
 12390    0
 10617    0
 4337     0
 Name: churn, Length: 2922, dtype: int64]

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

In [19]:
rf.fit(X_train , y_train)

RandomForestClassifier(random_state=42)

In [20]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

In [21]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [22]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.9086242299794661
Precision: 0.8148148148148148
Recall   : 0.07746478873239436
F1 Score : 0.1414790996784566
ROC AUC  : 0.6920075227711988

In [23]:
print(confusion_matrix(y_test, y_pred))

[[2633    5]
 [ 262   22]]

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95      2638
           1       0.81      0.08      0.14       284

    accuracy                           0.91      2922
   macro avg       0.86      0.54      0.55      2922
weighted avg       0.90      0.91      0.87      2922

In [25]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

In [26]:
y_train_sm.value_counts()

churn
0    10549
1    10549
Name: count, dtype: int64

In [27]:
rf = RandomForestClassifier(random_state=42)

rf.fit(X_train_sm, y_train_sm)

RandomForestClassifier(random_state=42)

In [28]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:,1]

In [29]:
(
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

(<function sklearn.metrics._classification.accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)>,
 <function sklearn.metrics._classification.precision_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 <function sklearn.metrics._ranking.roc_auc_score(y_true, y_score, *, average='macro', sample_weight=None, max_fpr=None, multi_class='raise', labels=None)>,
 <function sklearn.metrics._classification.confusion_matrix(y_true, y_pred, *, labels=None, sample_weight=None, normalize=None)>,
 <function sklearn.metrics._classification.classification_report(y_true, y_pred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')>)

In [30]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.9065708418891171
Precision: 0.6341463414634146
Recall   : 0.09154929577464789
F1 Score : 0.16
ROC AUC  : 0.6894654507789725

In [31]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2623   15]
 [ 258   26]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95      2638
           1       0.63      0.09      0.16       284

    accuracy                           0.91      2922
   macro avg       0.77      0.54      0.56      2922
weighted avg       0.88      0.91      0.87      2922

In [32]:
rf = RandomForestClassifier(
    random_state=42,
    class_weight='balanced'
)

In [33]:
RandomForestClassifier(random_state=42)

RandomForestClassifier(random_state=42)

In [34]:
RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=10,
    class_weight='balanced',
    random_state=42
)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=10, n_estimators=300, random_state=42)

In [36]:
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [37]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:,1]

In [38]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.9099931553730322
Precision: 0.8888888888888888
Recall   : 0.08450704225352113
F1 Score : 0.15434083601286175
ROC AUC  : 0.6996083780926652
[[2635    3]
 [ 260   24]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95      2638
           1       0.89      0.08      0.15       284

    accuracy                           0.91      2922
   macro avg       0.90      0.54      0.55      2922
weighted avg       0.91      0.91      0.87      2922

In [39]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance.head(10)

                    Feature  Importance
13       margin_net_pow_ele    0.051309
12     margin_gross_pow_ele    0.048926
1                  cons_12m    0.046606
6   forecast_meter_rent_12m    0.046118
0                Unnamed: 0    0.044211
15               net_margin    0.041424
4         forecast_cons_12m    0.041408
3           cons_last_month    0.036501
16                  pow_max    0.031904
50             months_activ    0.031070